apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-contact-deployment
  labels:
    app: delete-contact
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delete-contact
  template:
    metadata:
      labels:
        app: delete-contact
    spec:
      containers:
      - name: delete-contact
        image: dalileme/delete-contact:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey
