apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-contact-deployment
  labels:
    app: update-contact
spec:
  replicas: 2
  selector:
    matchLabels:
      app: update-contact
  template:
    metadata:
      labels:
        app: update-contact
    spec:
      containers:
      - name: update-contact
        image: dalileme/update-contact:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey
